### ISSUE TITLE
columnTypes query does not escape tablename 

### ISSUE THREAD

**Issue by ghstahl** [jimsmart/schema#10]
I am testing using the following sqlserver image.
```
 sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql 
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2
```
The queries for getting colum types in the various dialect_{{type}}.go are 
```
mssql 
`SELECT * FROM %s WHERE 1=0`,
```
vs
``` 
mysql
`SELECT * FROM %s LIMIT 0`,
```

Some real examples, 
```
mssql 
SELECT * FROM Vehicle WHERE 1=0
```
```
mssql 
SELECT * FROM `Vehicle` WHERE 1=0
 "Incorrect syntax near '`'."
```
```
mysql
SELECT * FROM `Vehicle`  LIMIT 0
```

I would think that the dialect_mysql.go should account for the back-ticks.  I haven't tested this on a mysql image, so I don't know for sure.
```
`SELECT * FROM `%s` LIMIT 0`,
```

Upstream customers of the schema library, for all database types, are [passing in](https://github.com/smallnest/gen/blob/master/dbmeta/meta.go#L89)  
```
"`"+tablename+"`"
```
where they should have just been passing in 
```
tablename
```

Whose responsibility is it to know the different variations of a tablename?
upstream customers or the schema library?

If its the schema library then we have a breaking change because upstream libraries are passing in 
```
"`"+tablename+"`"
```
